export enum ActionTypes {
    SET_DATES = 'SET_DATES',
    RESET_DATES = 'RESET_DATES',
    SET_SCALES = 'SET_SCALES',
    RESET_SCALES = 'RESET_SCALES',
    SET_STATE = 'SET_STATE',
    RESET_STATE = 'RESET_STATE'
}
